# Generated by Django 3.1.7 on 2021-03-18 22:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satelite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('_distance', models.FloatField(default=0.0)),
                ('_latitude', models.FloatField(null=True)),
                ('_longitude', models.FloatField(null=True)),
                ('_message', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
